### ISSUE TITLE
Copy and pasting from external source to Yopta Editor adds unwanted new lines

### ISSUE THREAD

**Issue by ofgowtham** [Darginec05/Yopta-Editor#78] opened 2023-09-13 14:40 UTC
**Describe the bug**
Copy and pasting from external source to Yopta Editor adds unwanted new lines

**To Reproduce**
1. Copy from any article, for example wikipedia
2. Paste it in the Yopta Editor

**Expected behavior**
The unwanted newlines should not be added when pasting.

**Screenshots**

https://github.com/Darginec05/Yopta-Editor/assets/24489435/ce29e7ab-22d1-4b77-8f4d-72889e52ca80

Desktop (please complete the following information):

OS: Windows 11 22621.1702
Browser: Chrome 113.0.5672.93
Version :
"@stripe/stripe-js": "^1.52.1",
"@yoopta/action-menu-list": "^1.9.5-rc",
"@yoopta/blockquote": "^1.9.6-rc",
"@yoopta/callout": "^1.9.5-rc",
"@yoopta/code": "^1.9.5-rc",
"@yoopta/editor": "1.9.9-rc",
"@yoopta/embed": "^1.9.5-rc",
"@yoopta/headings": "^1.9.5-rc",
"@yoopta/image": "^1.9.5-rc",
"@yoopta/link": "^1.9.5-rc",
"@yoopta/lists": "^1.9.5-rc",
"@yoopta/marks": "^1.9.5-rc",
"@yoopta/paragraph": "^1.9.7-rc",
"@yoopta/renderer": "^1.9.5-rc",
"@yoopta/toolbar": "^1.9.5-rc",
"@yoopta/video": "^1.9.5-rc",

**Comment by Darginec05** [comment] 2023-09-14 16:56
Can you please check copy/paste with this version of editor @yoopta/editor@1.9.21-rc?

**Comment by Darginec05** [comment] 2023-09-21 18:25
Fixed in @yoopta/editor@1.9.22-rc

**Comment by Darginec05** [comment] 2023-09-22 15:39
Reopened because the error is reproduced in Windows platform

**Comment by Darginec05** [comment] 2023-09-22 18:21
The last issue was fixed in @yoopta/editor@1.9.25-rc

**Closed** 2023-09-22 18:35 UTC
Labels: bug
